require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/attendences", type: :request do
  
  # Attendence. As you add validations to Attendence, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Attendence.create! valid_attributes
      get attendences_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      attendence = Attendence.create! valid_attributes
      get attendence_url(attendence)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_attendence_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      attendence = Attendence.create! valid_attributes
      get edit_attendence_url(attendence)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Attendence" do
        expect {
          post attendences_url, params: { attendence: valid_attributes }
        }.to change(Attendence, :count).by(1)
      end

      it "redirects to the created attendence" do
        post attendences_url, params: { attendence: valid_attributes }
        expect(response).to redirect_to(attendence_url(Attendence.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Attendence" do
        expect {
          post attendences_url, params: { attendence: invalid_attributes }
        }.to change(Attendence, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post attendences_url, params: { attendence: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested attendence" do
        attendence = Attendence.create! valid_attributes
        patch attendence_url(attendence), params: { attendence: new_attributes }
        attendence.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the attendence" do
        attendence = Attendence.create! valid_attributes
        patch attendence_url(attendence), params: { attendence: new_attributes }
        attendence.reload
        expect(response).to redirect_to(attendence_url(attendence))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        attendence = Attendence.create! valid_attributes
        patch attendence_url(attendence), params: { attendence: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested attendence" do
      attendence = Attendence.create! valid_attributes
      expect {
        delete attendence_url(attendence)
      }.to change(Attendence, :count).by(-1)
    end

    it "redirects to the attendences list" do
      attendence = Attendence.create! valid_attributes
      delete attendence_url(attendence)
      expect(response).to redirect_to(attendences_url)
    end
  end
end
