require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/leafs", type: :request do
  
  # Leaf. As you add validations to Leaf, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Leaf.create! valid_attributes
      get leafs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      leaf = Leaf.create! valid_attributes
      get leaf_url(leaf)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_leaf_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      leaf = Leaf.create! valid_attributes
      get edit_leaf_url(leaf)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Leaf" do
        expect {
          post leafs_url, params: { leaf: valid_attributes }
        }.to change(Leaf, :count).by(1)
      end

      it "redirects to the created leaf" do
        post leafs_url, params: { leaf: valid_attributes }
        expect(response).to redirect_to(leaf_url(Leaf.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Leaf" do
        expect {
          post leafs_url, params: { leaf: invalid_attributes }
        }.to change(Leaf, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post leafs_url, params: { leaf: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested leaf" do
        leaf = Leaf.create! valid_attributes
        patch leaf_url(leaf), params: { leaf: new_attributes }
        leaf.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the leaf" do
        leaf = Leaf.create! valid_attributes
        patch leaf_url(leaf), params: { leaf: new_attributes }
        leaf.reload
        expect(response).to redirect_to(leaf_url(leaf))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        leaf = Leaf.create! valid_attributes
        patch leaf_url(leaf), params: { leaf: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested leaf" do
      leaf = Leaf.create! valid_attributes
      expect {
        delete leaf_url(leaf)
      }.to change(Leaf, :count).by(-1)
    end

    it "redirects to the leafs list" do
      leaf = Leaf.create! valid_attributes
      delete leaf_url(leaf)
      expect(response).to redirect_to(leafs_url)
    end
  end
end
