require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/leave_balances", type: :request do
  
  # LeaveBalance. As you add validations to LeaveBalance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LeaveBalance.create! valid_attributes
      get leave_balances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      leave_balance = LeaveBalance.create! valid_attributes
      get leave_balance_url(leave_balance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_leave_balance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      leave_balance = LeaveBalance.create! valid_attributes
      get edit_leave_balance_url(leave_balance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LeaveBalance" do
        expect {
          post leave_balances_url, params: { leave_balance: valid_attributes }
        }.to change(LeaveBalance, :count).by(1)
      end

      it "redirects to the created leave_balance" do
        post leave_balances_url, params: { leave_balance: valid_attributes }
        expect(response).to redirect_to(leave_balance_url(LeaveBalance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LeaveBalance" do
        expect {
          post leave_balances_url, params: { leave_balance: invalid_attributes }
        }.to change(LeaveBalance, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post leave_balances_url, params: { leave_balance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested leave_balance" do
        leave_balance = LeaveBalance.create! valid_attributes
        patch leave_balance_url(leave_balance), params: { leave_balance: new_attributes }
        leave_balance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the leave_balance" do
        leave_balance = LeaveBalance.create! valid_attributes
        patch leave_balance_url(leave_balance), params: { leave_balance: new_attributes }
        leave_balance.reload
        expect(response).to redirect_to(leave_balance_url(leave_balance))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        leave_balance = LeaveBalance.create! valid_attributes
        patch leave_balance_url(leave_balance), params: { leave_balance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested leave_balance" do
      leave_balance = LeaveBalance.create! valid_attributes
      expect {
        delete leave_balance_url(leave_balance)
      }.to change(LeaveBalance, :count).by(-1)
    end

    it "redirects to the leave_balances list" do
      leave_balance = LeaveBalance.create! valid_attributes
      delete leave_balance_url(leave_balance)
      expect(response).to redirect_to(leave_balances_url)
    end
  end
end
